name: oficina.oficinamecanica.com deployment

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: echo Building the app
      
  deploy-production:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: ${{ vars.URL }}
    needs: build
    steps:
      - name: Repo Checkout
        uses: actions/checkout@v2

      - name: Create Exclude File
        run: |
          echo ".git/" > .rsync-exclude
          echo "node_modules/" >> .rsync-exclude
          echo "storage/" >> .rsync-exclude
          echo ".env" >> .rsync-exclude
          git ls-files --ignored --exclude-standard -o >> .rsync-exclude

      - name: Hostgator Deployment
        uses: easingthemes/ssh-deploy@v2.1.5
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-avz --exclude-from='.rsync-exclude' --update"
          SOURCE: "./"
          REMOTE_HOST: ${{ vars.REMOTE_HOST }}
          REMOTE_USER: ${{ vars.REMOTE_USER }}
          REMOTE_PORT: ${{ vars.REMOTE_PORT }}
          TARGET: ${{ vars.TARGET }}