name: oficina.oficinamecanica.com deployment

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: echo Building the app
      
  deploy-development:
    runs-on: ubuntu-latest
    environment:
      name: development
      url: ${{ vars.URL }}
    needs: build
    steps:
      - name: Repo Checkout
        uses: actions/checkout@v2
      - name: Hostgator Deployment
        uses: easingthemes/ssh-deploy@v2.1.5
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-rlgoDzvc --delete"
          SOURCE: "/public_html/"
          REMOTE_HOST: ${{ vars.REMOTE_HOST }}
          REMOTE_USER: ${{ vars.REMOTE_USER }}
          REMOTE_PORT: ${{ vars.REMOTE_PORT }}
          TARGET: ${{ vars.TARGET }}

  deploy-staging:
    runs-on: ubuntu-latest
    environment:
      name: staging
      url: ${{ vars.URL }}
    needs: deploy-development
    steps:
      - name: Repo Checkout
        uses: actions/checkout@v2
      - name: Hostgator Deployment
        uses: easingthemes/ssh-deploy@v2.1.5
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-rlgoDzvc --delete"
          SOURCE: "/public_html/"
          REMOTE_HOST: ${{ vars.REMOTE_HOST }}
          REMOTE_USER: ${{ vars.REMOTE_USER }}
          REMOTE_PORT: ${{ vars.REMOTE_PORT }}
          TARGET: ${{ vars.TARGET }}

  deploy-production: 
      runs-on: ubuntu-latest
      environment:
        name: staging
        url: ${{ vars.URL }}
      needs: deploy-development
      steps:
        - name: Repo Checkout
          uses: actions/checkout@v2
        - name: Hostgator Deployment
          uses: easingthemes/ssh-deploy@v2.1.5
          with:
            SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
            ARGS: "-rlgoDzvc --delete"
            SOURCE: "/public_html/"
            REMOTE_HOST: ${{ vars.REMOTE_HOST }}
            REMOTE_USER: ${{ vars.REMOTE_USER }}
            REMOTE_PORT: ${{ vars.REMOTE_PORT }}
            TARGET: ${{ vars.TARGET }}